[project]
name = "grand-tour-dataloader"
version = "0.1.0"
description = "Dataloader for the Grand Tour legged robotics dataset"
readme = "README.md"
authors = [
    { email = "laurence.w.liang@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=0.26.0",
    "ruff>=0.14.14",
    "zarr>=2.18.0",
    "matplotlib>=3.8.0",
    "numpy>=1.26.0",
    "pillow>=10.0.0",
]

[project.scripts]
grand-tour-dataloader = "grand_tour_dataloader:main"

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"
